### ISSUE TITLE
Bug: Base Service unmask `exec` is incorrect.

### ISSUE THREAD

**Issue by ianc769** [simp/pupmod-simp-nfs#109]
[manifests/base/service.pp](https://github.com/simp/pupmod-simp-nfs/blob/master/manifests/base/service.pp#L72-L76)

Exec should be ```command => '/usr/bin/systemctl unmask rpc-gssd.service',```

This causes puppet to run loop in specific configuration.

**Comment by silug** [comment]
@ianc769 Thanks for the heads-up!

Is there any chance you could review or test https://github.com/simp/pupmod-simp-nfs/pull/110?
